Encoding:
  Enabled: false

LineLength:
  Max: 300

HashSyntax:
  EnforcedStyle: hash_rockets

IfUnlessModifier:
  Enabled: false

MethodLength:
  Max: 11

ClassLength:
  Max: 200

TrivialAccessors:
  ExactNameMatch: true
