name             'chef-splunk'
maintainer       'httpstergeek.com'
maintainer_email 'bmacias@httpstergeek.com'
license          'All rights reserved'
description      'Installs/Configures chef-splunk'
long_description 'Installs/Configures Splunk for a distributed environment.  Assume separate rolls for indexer, search, search head pool/license, and deployment server'
version          '0.5.20'
depends          'chef-vault', '>= 1.0.4'
depends          'nfs'
depends          'nix_server'
depends          'java'
