name             'chef-splunk'
maintainer       'Bernardo Macias'
maintainer_email 'bmacias84@gmail.com'
license          'All rights reserved'
description      'Installs/Configures chef-splunk'
long_description 'Installs/Configures Splunk for a distributed environment.  Assume separate rolls for indexer, search, search head pool/license, and deployment server'
version          '1.0.0'
depends          'chef-vault', '>= 1.0.4'
depends          'nfs'
